comicbin/config/routes.rb
Comicbin::Application.routes.draw do
  resources :comics
end

comicbin/app/models/comic.rb
class Comic < ActiveRecord::Base
end

comicbin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

comicbin/app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  def index
    @comics = Comic.all
    # render 'index'
  end

  def show
    @comic = Comic.find_by :id => params[:id]
    render 'show'
  end

  def destroy
    @comicToDestroy = Comic.find_by :id => params[:id]
    @comicToDestroy.destroy
    redirect_to "/comics"
  end

  def new
    @comic = Comic.new
    render 'new'
  end

  def create
   @comic = Comic.new
   @comic.title = params[:comic][:title]
   @comic.description = params[:comic][:description]
   @comic.imageURL = params[:comic][:imageURL]
    if @comic.save
      redirect_to comics_path
    else
      render :action => 'new'
    end

  end
end

comicbin/app/helpers/application_helper.rb
module ApplicationHelper
end

comicbin/app/helpers/comics_helper.rb
module ComicsHelper
end

comicbin/app/views/comics/_form.html.erb
<div class='col-lg-6'>
  <div class='well'>

  <%= form_for(@comic,:method=>'post') do |c|%>

   <!-- WRITE THE CORRECT FORM HEADER AND BLOCK USING ERB -->


     <div class="form-group">
     <p>Title:</p><%= c.text_field :title, class: 'form-control' %>
      <!-- DISPLAY A TITLE LABEL -->
      <!-- DISPLAY A TEXT FIELD AND ATTACH THE CLASS OF 'form-control' TO THIS FIELD -->
    </div>
    <div class="form-group">
    <p>Description:</p><%= c.text_field :description, class: 'form-control' %>
      <!-- DISPLAY A DESCRIPTION LABEL -->
      <!-- DISPLAY A TEXT FIELD AND ATTACH THE CLASS OF 'form-control' TO THIS FIELD -->
    </div>
    <div class="form-group">
    <p>URL for cover image:</p><%= c.text_field :imageURL, class: 'form-control' %>
      <!-- DISPLAY AN IMAGE LABEL -->
      <!-- DISPLAY A TEXT FIELD ATTACH THE CLASS OF 'form-control' TO THIS FIELD -->
    </div>
    <div class="actions">
    <%= c.submit "Add comic", class: 'btn btn-primary' %>
      <!-- DISPLAY A SUBMIT BUTTON WITH A CLASS OF 'btn btn-primary' -->
    </div>
    <% if @comic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

        <ul>
        <% @comic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>




  <% end %>
  </div>
</div>

comicbin/app/views/comics/edit.html.erb
<div class='container'>
  <h2>Edit comic</h2>
</div>

<div class='row'>
  <!-- RENDER THE FORM PARTIAL HERE. -->
</div>

<div class='container'>
  <%= link_to 'Show comic', @comic %>
  <%= link_to 'Back to all comics', comics_path %>
</div>

comicbin/app/views/comics/index.html.erb
<% @comics.in_groups_of(4, false).each_with_index do |group, index| %>
  <div class="row">
    <% group.each do |comic| %>
      <div class='col-lg-3 test'>
    <a href="comics/<%= comic.id.to_s %>"> <img class='img-responsive' src= <%= comic.imageURL %> ></a>
      </div>
    <% end %>
  </div>
<% end %>

comicbin/app/views/comics/new.html.erb
<div class='container'>
  <h2>Add a new comic</h2>
</div>

<div class='row'>
 <%= render "form" %>
</div>

<div class='container'>
  <%= link_to 'Back to all comics', comics_path %>
</div>

comicbin/app/views/comics/show.html.erb
<div class='row'>
  <div class='col-md-5'>
    <img class='img-responsive' src= <%= @comic.imageURL %>>
  </div>
  <div class='col-md-7'>
    <h1><%= @comic.title%></h1>
    <h4><%= @comic.description%></h4>
     <%= button_to "Delete comic book", { action: "destroy" , id: @comic.id },
                                method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-warning' %>
  </div>
</div>

comicbin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Comic Bin</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Oswald:400,700' %>
    <%= csrf_meta_tags %>
  </head>


  <body>
    <div class='container'>
      <div class='page-header'>
        <%= link_to 'Add a comic book', new_comic_path, class: 'btn btn-success pull-right add' %>
        <%= link_to 'View all comics', comics_path, class: 'btn btn-primary pull-right add' %>
        <h1 class='logo'>Comic Bin</h1>
      </div>
      <%= yield %>
    </div>
  </body>

</html>